### ISSUE TITLE
on board lamp (power-LED) is always on

### ISSUE THREAD

**Issue by Burkadius1952** [s60sc/ESP32-CAM_MJPEG2SD#45]
Hi ,after flashing the new release my problem is, that now the installed Lamp always is on. I can not swith it out. I do not use a microphon.
Can You help me agin ?
Best regards
Burkhard

**Comment by s60sc** [comment]
My fault, use latest mic.cpp

**Comment by Burkadius1952** [comment]
Ok,thanks . Will try it tomorrow.

**Comment by Burkadius1952** [comment]
Hi, I have installed the new mic.cpp. But the lamp is allways on. Microphone gain is „0“.
I’m using the GPIO12 ->PIR and the GPIO03 -> DS18…
Best Regards
Burkhard

**Comment by s60sc** [comment]
check startup log shows:
mic: Sound recording is Off

and check Lamp On is not selected

**Comment by burkadius** [comment]
I have checked this two things_
Mic:Sound recording is off and in the browser the lamp switch is off

???

**Comment by s60sc** [comment]
Try toggling on/off the lamp switch in browser. 
Try a different camera module if you have one.

**Comment by burkadius** [comment]
Toggeling on/off Ihave tried, no reaction
I will try tomorow a new camera moduel, but it is also AIThinker (I think so ???) It is absolutely the same.

Gesendet von Mail für Windows

Von: s60sc
Gesendet: Wednesday, 10 November 2021 17:44
An: s60sc/ESP32-CAM_MJPEG2SD
Cc: burkadius; Comment
Betreff: Re: [s60sc/ESP32-CAM_MJPEG2SD] on board lamp (power-LED) is always on(Issue #45)

Try toggling on/off the lamp switch in browser.
Try a different camera module if you have one.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
